include $(TOPDIR)/rules.mk

LUCI_TITLE:=Avantguard Theme
LUCI_DEPENDS:=+curl +jsonfilter
PKG_VERSION:=0.0.1
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature